/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AmanatRouteImport } from './routes/amanat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAmanatRouteImport } from './routes/admin/amanat'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as AdminMerchantsRouteImport } from './routes/admin/merchants'
import { Route as AdminPickupPointsRouteImport } from './routes/admin.pickup-points'
import { Route as AdminShipmentsRouteImport } from './routes/admin.shipments'
import { Route as AmanatNewRouteImport } from './routes/amanat.new'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as MerchantAmanatRouteImport } from './routes/merchant.amanat'
import { Route as MerchantCustomersRouteImport } from './routes/merchant.customers'
import { Route as MerchantLeaderboardRouteImport } from './routes/merchant.leaderboard'
import { Route as MerchantMarketingRouteImport } from './routes/merchant.marketing'
import { Route as MerchantNotificationsRouteImport } from './routes/merchant.notifications'
import { Route as MerchantOrdersRouteImport } from './routes/merchant.orders'
import { Route as MerchantReportsRouteImport } from './routes/merchant.reports'
import { Route as MerchantSettingsRouteImport } from './routes/merchant.settings'
import { Route as MerchantSupportRouteImport } from './routes/merchant.support'
import { Route as MerchantWalletRouteImport } from './routes/merchant.wallet'
import { Route as ShipmentsNewRouteImport } from './routes/shipments.new'
import { Route as MerchantAmanatNewRouteImport } from './routes/merchant.amanat.new'
import { Route as MerchantDashboardBackupRouteImport } from './routes/merchant.dashboard.backup'
import { Route as MerchantIndexBeforeLayoutFixRouteImport } from './routes/merchant.index.before-layout-fix'
import { Route as MerchantShipmentsNewRouteImport } from './routes/merchant.shipments.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AmanatRoute = AmanatRouteImport.update({
  id: '/amanat',
  path: '/amanat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAmanatRoute = AdminAmanatRouteImport.update({
  id: '/admin/amanat',
  path: '/admin/amanat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/admin/cities',
  path: '/admin/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/admin/merchants',
  path: '/admin/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPickupPointsRoute = AdminPickupPointsRouteImport.update({
  id: '/admin/pickup-points',
  path: '/admin/pickup-points',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShipmentsRoute = AdminShipmentsRouteImport.update({
  id: '/admin/shipments',
  path: '/admin/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const AmanatNewRoute = AmanatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AmanatRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantAmanatRoute = MerchantAmanatRouteImport.update({
  id: '/amanat',
  path: '/amanat',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantCustomersRoute = MerchantCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantLeaderboardRoute = MerchantLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantMarketingRoute = MerchantMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantNotificationsRoute = MerchantNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantReportsRoute = MerchantReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantSettingsRoute = MerchantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantSupportRoute = MerchantSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantWalletRoute = MerchantWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => MerchantRoute,
} as any)
const ShipmentsNewRoute = ShipmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShipmentsRoute,
} as any)
const MerchantAmanatNewRoute = MerchantAmanatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MerchantAmanatRoute,
} as any)
const MerchantDashboardBackupRoute = MerchantDashboardBackupRouteImport.update({
  id: '/dashboard/backup',
  path: '/dashboard/backup',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantIndexBeforeLayoutFixRoute =
  MerchantIndexBeforeLayoutFixRouteImport.update({
    id: '/index/before-layout-fix',
    path: '/index/before-layout-fix',
    getParentRoute: () => MerchantRoute,
  } as any)
const MerchantShipmentsNewRoute = MerchantShipmentsNewRouteImport.update({
  id: '/shipments/new',
  path: '/shipments/new',
  getParentRoute: () => MerchantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/amanat': typeof AmanatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRouteWithChildren
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/admin/amanat': typeof AdminAmanatRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/pickup-points': typeof AdminPickupPointsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/amanat/new': typeof AmanatNewRoute
  '/merchant/amanat': typeof MerchantAmanatRouteWithChildren
  '/merchant/customers': typeof MerchantCustomersRoute
  '/merchant/leaderboard': typeof MerchantLeaderboardRoute
  '/merchant/marketing': typeof MerchantMarketingRoute
  '/merchant/notifications': typeof MerchantNotificationsRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/reports': typeof MerchantReportsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/merchant/support': typeof MerchantSupportRoute
  '/merchant/wallet': typeof MerchantWalletRoute
  '/shipments/new': typeof ShipmentsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/merchant/amanat/new': typeof MerchantAmanatNewRoute
  '/merchant/dashboard/backup': typeof MerchantDashboardBackupRoute
  '/merchant/shipments/new': typeof MerchantShipmentsNewRoute
  '/merchant/index/before-layout-fix': typeof MerchantIndexBeforeLayoutFixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/amanat': typeof AmanatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRouteWithChildren
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/admin/amanat': typeof AdminAmanatRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/pickup-points': typeof AdminPickupPointsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/amanat/new': typeof AmanatNewRoute
  '/merchant/amanat': typeof MerchantAmanatRouteWithChildren
  '/merchant/customers': typeof MerchantCustomersRoute
  '/merchant/leaderboard': typeof MerchantLeaderboardRoute
  '/merchant/marketing': typeof MerchantMarketingRoute
  '/merchant/notifications': typeof MerchantNotificationsRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/reports': typeof MerchantReportsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/merchant/support': typeof MerchantSupportRoute
  '/merchant/wallet': typeof MerchantWalletRoute
  '/shipments/new': typeof ShipmentsNewRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/merchant/amanat/new': typeof MerchantAmanatNewRoute
  '/merchant/dashboard/backup': typeof MerchantDashboardBackupRoute
  '/merchant/shipments/new': typeof MerchantShipmentsNewRoute
  '/merchant/index/before-layout-fix': typeof MerchantIndexBeforeLayoutFixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/amanat': typeof AmanatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRouteWithChildren
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/admin/amanat': typeof AdminAmanatRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/pickup-points': typeof AdminPickupPointsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/amanat/new': typeof AmanatNewRoute
  '/merchant/amanat': typeof MerchantAmanatRouteWithChildren
  '/merchant/customers': typeof MerchantCustomersRoute
  '/merchant/leaderboard': typeof MerchantLeaderboardRoute
  '/merchant/marketing': typeof MerchantMarketingRoute
  '/merchant/notifications': typeof MerchantNotificationsRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/reports': typeof MerchantReportsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/merchant/support': typeof MerchantSupportRoute
  '/merchant/wallet': typeof MerchantWalletRoute
  '/shipments/new': typeof ShipmentsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/merchant/amanat/new': typeof MerchantAmanatNewRoute
  '/merchant/dashboard/backup': typeof MerchantDashboardBackupRoute
  '/merchant/shipments/new': typeof MerchantShipmentsNewRoute
  '/merchant/index/before-layout-fix': typeof MerchantIndexBeforeLayoutFixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/amanat'
    | '/dashboard'
    | '/faq'
    | '/help'
    | '/login'
    | '/merchant'
    | '/notifications'
    | '/privacy'
    | '/register'
    | '/settings'
    | '/shipments'
    | '/shipping-policy'
    | '/terms'
    | '/admin/amanat'
    | '/admin/cities'
    | '/admin/merchants'
    | '/admin/pickup-points'
    | '/admin/shipments'
    | '/amanat/new'
    | '/merchant/amanat'
    | '/merchant/customers'
    | '/merchant/leaderboard'
    | '/merchant/marketing'
    | '/merchant/notifications'
    | '/merchant/orders'
    | '/merchant/reports'
    | '/merchant/settings'
    | '/merchant/support'
    | '/merchant/wallet'
    | '/shipments/new'
    | '/admin/'
    | '/merchant/'
    | '/merchant/amanat/new'
    | '/merchant/dashboard/backup'
    | '/merchant/shipments/new'
    | '/merchant/index/before-layout-fix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/amanat'
    | '/dashboard'
    | '/faq'
    | '/help'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/register'
    | '/settings'
    | '/shipments'
    | '/shipping-policy'
    | '/terms'
    | '/admin/amanat'
    | '/admin/cities'
    | '/admin/merchants'
    | '/admin/pickup-points'
    | '/admin/shipments'
    | '/amanat/new'
    | '/merchant/amanat'
    | '/merchant/customers'
    | '/merchant/leaderboard'
    | '/merchant/marketing'
    | '/merchant/notifications'
    | '/merchant/orders'
    | '/merchant/reports'
    | '/merchant/settings'
    | '/merchant/support'
    | '/merchant/wallet'
    | '/shipments/new'
    | '/admin'
    | '/merchant'
    | '/merchant/amanat/new'
    | '/merchant/dashboard/backup'
    | '/merchant/shipments/new'
    | '/merchant/index/before-layout-fix'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/amanat'
    | '/dashboard'
    | '/faq'
    | '/help'
    | '/login'
    | '/merchant'
    | '/notifications'
    | '/privacy'
    | '/register'
    | '/settings'
    | '/shipments'
    | '/shipping-policy'
    | '/terms'
    | '/admin/amanat'
    | '/admin/cities'
    | '/admin/merchants'
    | '/admin/pickup-points'
    | '/admin/shipments'
    | '/amanat/new'
    | '/merchant/amanat'
    | '/merchant/customers'
    | '/merchant/leaderboard'
    | '/merchant/marketing'
    | '/merchant/notifications'
    | '/merchant/orders'
    | '/merchant/reports'
    | '/merchant/settings'
    | '/merchant/support'
    | '/merchant/wallet'
    | '/shipments/new'
    | '/admin/'
    | '/merchant/'
    | '/merchant/amanat/new'
    | '/merchant/dashboard/backup'
    | '/merchant/shipments/new'
    | '/merchant/index/before-layout-fix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AmanatRoute: typeof AmanatRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRouteWithChildren
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  TermsRoute: typeof TermsRoute
  AdminAmanatRoute: typeof AdminAmanatRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminPickupPointsRoute: typeof AdminPickupPointsRoute
  AdminShipmentsRoute: typeof AdminShipmentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amanat': {
      id: '/amanat'
      path: '/amanat'
      fullPath: '/amanat'
      preLoaderRoute: typeof AmanatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/amanat': {
      id: '/admin/amanat'
      path: '/admin/amanat'
      fullPath: '/admin/amanat'
      preLoaderRoute: typeof AdminAmanatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/admin/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/admin/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pickup-points': {
      id: '/admin/pickup-points'
      path: '/admin/pickup-points'
      fullPath: '/admin/pickup-points'
      preLoaderRoute: typeof AdminPickupPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipments': {
      id: '/admin/shipments'
      path: '/admin/shipments'
      fullPath: '/admin/shipments'
      preLoaderRoute: typeof AdminShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amanat/new': {
      id: '/amanat/new'
      path: '/new'
      fullPath: '/amanat/new'
      preLoaderRoute: typeof AmanatNewRouteImport
      parentRoute: typeof AmanatRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/amanat': {
      id: '/merchant/amanat'
      path: '/amanat'
      fullPath: '/merchant/amanat'
      preLoaderRoute: typeof MerchantAmanatRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/customers': {
      id: '/merchant/customers'
      path: '/customers'
      fullPath: '/merchant/customers'
      preLoaderRoute: typeof MerchantCustomersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/leaderboard': {
      id: '/merchant/leaderboard'
      path: '/leaderboard'
      fullPath: '/merchant/leaderboard'
      preLoaderRoute: typeof MerchantLeaderboardRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/marketing': {
      id: '/merchant/marketing'
      path: '/marketing'
      fullPath: '/merchant/marketing'
      preLoaderRoute: typeof MerchantMarketingRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/notifications': {
      id: '/merchant/notifications'
      path: '/notifications'
      fullPath: '/merchant/notifications'
      preLoaderRoute: typeof MerchantNotificationsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/reports': {
      id: '/merchant/reports'
      path: '/reports'
      fullPath: '/merchant/reports'
      preLoaderRoute: typeof MerchantReportsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/settings': {
      id: '/merchant/settings'
      path: '/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof MerchantSettingsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/support': {
      id: '/merchant/support'
      path: '/support'
      fullPath: '/merchant/support'
      preLoaderRoute: typeof MerchantSupportRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/wallet': {
      id: '/merchant/wallet'
      path: '/wallet'
      fullPath: '/merchant/wallet'
      preLoaderRoute: typeof MerchantWalletRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/shipments/new': {
      id: '/shipments/new'
      path: '/new'
      fullPath: '/shipments/new'
      preLoaderRoute: typeof ShipmentsNewRouteImport
      parentRoute: typeof ShipmentsRoute
    }
    '/merchant/amanat/new': {
      id: '/merchant/amanat/new'
      path: '/new'
      fullPath: '/merchant/amanat/new'
      preLoaderRoute: typeof MerchantAmanatNewRouteImport
      parentRoute: typeof MerchantAmanatRoute
    }
    '/merchant/dashboard/backup': {
      id: '/merchant/dashboard/backup'
      path: '/dashboard/backup'
      fullPath: '/merchant/dashboard/backup'
      preLoaderRoute: typeof MerchantDashboardBackupRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/index/before-layout-fix': {
      id: '/merchant/index/before-layout-fix'
      path: '/index/before-layout-fix'
      fullPath: '/merchant/index/before-layout-fix'
      preLoaderRoute: typeof MerchantIndexBeforeLayoutFixRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/shipments/new': {
      id: '/merchant/shipments/new'
      path: '/shipments/new'
      fullPath: '/merchant/shipments/new'
      preLoaderRoute: typeof MerchantShipmentsNewRouteImport
      parentRoute: typeof MerchantRoute
    }
  }
}

interface AmanatRouteChildren {
  AmanatNewRoute: typeof AmanatNewRoute
}

const AmanatRouteChildren: AmanatRouteChildren = {
  AmanatNewRoute: AmanatNewRoute,
}

const AmanatRouteWithChildren =
  AmanatRoute._addFileChildren(AmanatRouteChildren)

interface MerchantAmanatRouteChildren {
  MerchantAmanatNewRoute: typeof MerchantAmanatNewRoute
}

const MerchantAmanatRouteChildren: MerchantAmanatRouteChildren = {
  MerchantAmanatNewRoute: MerchantAmanatNewRoute,
}

const MerchantAmanatRouteWithChildren = MerchantAmanatRoute._addFileChildren(
  MerchantAmanatRouteChildren,
)

interface MerchantRouteChildren {
  MerchantAmanatRoute: typeof MerchantAmanatRouteWithChildren
  MerchantCustomersRoute: typeof MerchantCustomersRoute
  MerchantLeaderboardRoute: typeof MerchantLeaderboardRoute
  MerchantMarketingRoute: typeof MerchantMarketingRoute
  MerchantNotificationsRoute: typeof MerchantNotificationsRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantReportsRoute: typeof MerchantReportsRoute
  MerchantSettingsRoute: typeof MerchantSettingsRoute
  MerchantSupportRoute: typeof MerchantSupportRoute
  MerchantWalletRoute: typeof MerchantWalletRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  MerchantDashboardBackupRoute: typeof MerchantDashboardBackupRoute
  MerchantShipmentsNewRoute: typeof MerchantShipmentsNewRoute
  MerchantIndexBeforeLayoutFixRoute: typeof MerchantIndexBeforeLayoutFixRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantAmanatRoute: MerchantAmanatRouteWithChildren,
  MerchantCustomersRoute: MerchantCustomersRoute,
  MerchantLeaderboardRoute: MerchantLeaderboardRoute,
  MerchantMarketingRoute: MerchantMarketingRoute,
  MerchantNotificationsRoute: MerchantNotificationsRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantReportsRoute: MerchantReportsRoute,
  MerchantSettingsRoute: MerchantSettingsRoute,
  MerchantSupportRoute: MerchantSupportRoute,
  MerchantWalletRoute: MerchantWalletRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  MerchantDashboardBackupRoute: MerchantDashboardBackupRoute,
  MerchantShipmentsNewRoute: MerchantShipmentsNewRoute,
  MerchantIndexBeforeLayoutFixRoute: MerchantIndexBeforeLayoutFixRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

interface ShipmentsRouteChildren {
  ShipmentsNewRoute: typeof ShipmentsNewRoute
}

const ShipmentsRouteChildren: ShipmentsRouteChildren = {
  ShipmentsNewRoute: ShipmentsNewRoute,
}

const ShipmentsRouteWithChildren = ShipmentsRoute._addFileChildren(
  ShipmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AmanatRoute: AmanatRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRouteWithChildren,
  ShippingPolicyRoute: ShippingPolicyRoute,
  TermsRoute: TermsRoute,
  AdminAmanatRoute: AdminAmanatRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminPickupPointsRoute: AdminPickupPointsRoute,
  AdminShipmentsRoute: AdminShipmentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
